### ISSUE TITLE
OSS maintainer that uses 1Password, but not needed for project....

### ISSUE THREAD

**Issue by palfrey** [1Password/1password-teams-open-source#555]
Hiya folks. I'm the core dev/owner for https://github.com/palfrey/serial_test an OSS project with >4 million downloads (and [one of your devs potentially using it](https://github.com/palfrey/serial_test/pull/62)).

The project itself doesn't need 1Password, as there's no secrets to store (well, barring my Github login, but that's not project-specific obviously). However, myself and my spouse use 1Password Families for all our personal stuff and I was wondering if that could be covered under this? I get that it's not the standard offer detailed in this repo, but something covering that would be the thing that would actually help me.

Any thoughts?

**Comment by oliverdunk** [comment]
Hey @palfrey! Thanks for your work on serial_test - projects like yours help to make 1Password possible.

With the Teams account, we can be slightly flexible. Even if you're not using it for one specific project, if it's helping you to store credentials and keep your open source projects more secure, I think that's totally fine.

If you do specifically want a families account - we unfortunately can't apply this promotion because of how it is setup internally. That said, please do drop an email to opensource@1password.com mentioning me and I'll see what we can do!
